conditions:
- humidity > threshold
constants:
  threshold: 80
schedule:
  minutes: 60
  trigger: interval
severity: info
text: The humidity is very high (%humidity%%)
variables:
  humidity: examples/new_york/humidity
