conditions: []
schedule:
  hour: 23
  minute: 59
  second: 0
  trigger: cron
severity: info
text: "Today's average temperature has been %temperature_avg%\xB0C, the minimum %temperature_min%\xB0\
  C, the maximum %temperature_max%\xB0C"
variables:
  temperature_avg: examples/new_york/temperature/day/avg
  temperature_max: examples/new_york/temperature/day/max
  temperature_min: examples/new_york/temperature/day/min
