- Examples:
  - New York weather:
      icon: city
      page: examples/new_york
  - Widgets showcase:
      icon: chart-area
      page: examples/widgets
  - Services:
      icon: cogs
      page: examples/services

