- Status/Control widgets:
  - icon: hashtag
    sensor: examples/widgets/value
    size: 3
    title: Current Value
    type: value
  - sensor: examples/widgets/status
    size: 3
    title: Status
    type: status
  - icon: sliders-h
    sensor: examples/widgets/status
    size: 3
    title: On/Off Switch
    type: control
  - actions:
    - SET examples/widgets/status 1
    size: 3
    text: Set status to ON
    title: Button
    type: button
- ? ''
  : - sensor: examples/widgets/input_int
      size: 3
      title: Input Integer
      type: input
    - sensor: examples/widgets/input_float
      size: 3
      title: Input Float
      type: input
    - sensor: examples/widgets/input_string
      size: 3
      title: Input String
      type: input
- Timeseries widgets:
  - icon: chart-line
    sensors:
    - examples/widgets/value
    size: 3
    title: Summary Widget
    type: summary
  - sensors:
    - examples/widgets/value
    size: 4
    title: 'Timeline: Latest values'
    type: timeline
  - group_by: hour
    sensors:
    - examples/widgets/value
    size: 5
    title: 'Timeline: aggregate by hour'
    type: timeline
- ? ''
  : - group_by: day
      sensor: examples/widgets/value
      size: 4
      title: Daily Ranges
      type: range
    - group_by: day
      sensors:
      - examples/widgets/value
      size: 8
      title: 'Timeline: aggregate by day'
      type: timeline
- Image widgets:
  - sensor: examples/widgets/image
    size: 6
    title: Image
    type: image
- Calendar widgets:
  - sensor: examples/widgets/calendar
    size: 12
    title: Calendar/Scheduler
    type: calendar
