description: Condition Description
format: string
icon: cloud-sun
retain: last_value
service:
  configuration:
    latitude: 40.71
    longitude: -74
    request: description
  mode: active
  name: openweathermap
  schedule:
    minutes: 10
    trigger: interval
