calculate: avg_min_max
description: New York Weather Condition
format: string
icon: sun
retain: history
service:
  configuration:
    latitude: 40.71
    longitude: -74
    request: condition
  mode: active
  name: openweathermap
  schedule:
    minutes: 10
    trigger: interval
