description: New York Humidity
format: int
icon: tint
retain: last_value
service:
  configuration:
    latitude: 40.71
    longitude: -74
    request: humidity
  mode: active
  name: openweathermap
  schedule:
    minutes: 10
    trigger: interval
unit: '%'
