description: Image
format: image
icon: image
retain: single_value
service:
  configuration:
    url: http://images.opentopia.com/cams/6617/big.jpg
  mode: active
  name: image
  schedule:
    minutes: 10
    trigger: interval
